### ISSUE TITLE
Alt + ~ Hotkey not working

### ISSUE THREAD

**Issue by Zenoo** [JBarna/SpotifyKeep#1]
Hey,

I was trying out this little app, the playlist is created correctly and all, but whenever I try the Alt + ~ hotkey, nothing happens.
I don't really know what more to say, I'm running Windows 10.

**Comment by JBarna** [comment]
Oh no! I'll test this on my windows 10 computer and see if I can reproduce. I wonder if you already have something set to the `Alt + ~` hotkey?

**Comment by Zenoo** [comment]
No, I don't have anything set for `Alt +~}`

**Comment by JBarna** [comment]
@Zenoo hey so I did some digging into the runtime environemnt (Electron) that my app is built on top of. There's a known issue https://github.com/electron/electron/issues/10864 that notifications do not currently work on windows 10 for whatever reason. There's a few potential ways to get around that in the issue thread, that I might try to implement if I get time. However, I tested my app and although the notifications don't show up, it is infact still doing the song saving in the background. So you won't be notified sadly, but at least it will still save your song.

**Comment by Zenoo** [comment]
The `Keep` playlist isn't updating when I press `Alt + ~`. I don't really mind about the Windows 10 Notification, but if the song isn't saved in a Spotify Playlist, it's not really useful for me.

**Comment by FreshieGeek** [comment]
Last week when I installed it, it was working fine, but since the latest windows update on Tuesday, the key combo isn't working for me either.

**Comment by FreshieGeek** [comment]
> Last week when I installed it, it was working fine, but since the latest windows update on Tuesday, the key combo isn't working for me either.

I'm putting this here for posterity in case anyone else needs help. After doing a Disk Cleanup of system files of Windows Update, it's working again.

**Comment by bermontoto** [comment]
I'm on Mac and it does not work
