### ISSUE TITLE
Entirely stops working in Win 10 after sleep/hibernation

### ISSUE THREAD

**Issue by Paws-Deep** [JBarna/SpotifyKeep#14]
![Screenshot_23](https://user-images.githubusercontent.com/74794023/99845518-d50d5e80-2b85-11eb-8967-d7dbc3c01931.jpg)

Restarting Spotify and/of Spotify Keep doesn't help. Only the whole Win reboot.

**Comment by vadash** [comment]
Updated libs https://github.com/vadash/SpotifyKeep/releases/tag/1.2
Lets see if it helps. I am 0 with electron

**Comment by Paws-Deep** [comment]
> Updated libs https://github.com/vadash/SpotifyKeep/releases
> Lets see if it helps. I am 0 with electron

Sorry, I dont get it, how and where exactly can I download your updated version of this program?

**Comment by JBarna** [comment]
Please try with the new version
