### ISSUE TITLE
Crass language tooltips intended? Also an empty login window shows up at start

### ISSUE THREAD

**Issue by angstschweiss** [JBarna/SpotifyKeep#17]
The tray icon tooltip reads "google music is for cucks", while the menu sometimes displays the message "China #1"  with a chinese flag. Is this intended behavior? 

Additionally, an empty white window titled login pops up when starting the app.

These issues cause me to mistrust the application for now. Has the dev been compromised?

**Comment by JBarna** [comment]
Not sure why the window is popping up in the beginning - you can try re-installing the app. As for the other behavior you mentioned, those were included from the start for fun.
