### ISSUE TITLE
Add ability Sync back tracks....

### ISSUE THREAD

**Issue by Suleman-Elahi** [JBarna/SpotifyKeep#2]
Currently this tool adds a newly added song automatically in the library to "Keep" Playlist. But, if we remove a song from library, it doesn't remove that from "Keep" playlist. I wonder if that can be happen !!!

Thanks

**Comment by JBarna** [comment]
Removing tracks from the Keep playlist is not the intention as there are many times where I accidentally remove a song that I like from my liked songs and I use the Keep playlist to go find it and re-add it.
