### ISSUE TITLE
Add custom shortcut option

### ISSUE THREAD

**Issue by IGPenguin** [JBarna/SpotifyKeep#6]
its useless for me since I am using czech keyboard ://

**Comment by Spiz** [comment]
I would love to see this as well. I *love* that this program exists, but it would be so helpful to be able to change shortcut.

**Comment by crimzind** [comment]
I'd really like to echo the request for changeable hotkeys. I use Alt+` for Nvidia's GeForce Experience stuff. :(

**Comment by JBarna** [comment]
You can now update the hotkey in the new version.
