### ISSUE TITLE
Taking 30-60 seconds for song to get marked as liked and added to Keep playlist

### ISSUE THREAD

**Issue by PixelPoetix** [JBarna/SpotifyKeep#9]
Hello friend! First off, I'm stoked to have found someone who filled a need that Spotify continues to keep ignoring - a way to like the song that's playing with a keyboard shortcut! So thank you SO MUCH for building this marvelous little app!

I've successfully installed it on my Mac running Catalina and it DOES work. However, it takes anywhere from 30-60 seconds after I press the alt~ shortcut for it to actually mark the song as liked, add it to the keep playlist and notify me. I wasn't even sure it was working at first because it took so long, but then I saw the notification about a minute later.

This wouldn't be a dealbreaker if SpotifyKeep correctly likes/adds the song that was actually playing when I used the keyboard shortcut. But unfortunately, the downside is that if I hit the shortcut too close to the end of a song (less than a minute from the end), SpotifyKeep ends up liking and adding the NEXT song instead of the one I intended it to. This is problematic since that completely cancels out the efficiency of having a keyboard shortcut if I then have to constantly double check that SpotifyKeep saved the right song.

Any ideas?

**Comment by JBarna** [comment]
I'm curious if this is still happening for you. I can investigate on Mac.
